Action markdown /cgi-bin/strapdown.cgi
#Action markdown /cgi-bin/strapdown.cgi virtual
AddHandler markdown .md .mdh
DirectoryIndex index.html index.md index.mdh
PassEnv STRAPDOWN_DESCRIPTION
PassEnv STRAPDOWN_OG_DESCRIPTION
PassEnv STRAPDOWN_OG_IMAGE
PassEnv STRAPDOWN_OG_SITE_NAME
PassEnv STRAPDOWN_OG_TITLE
PassEnv STRAPDOWN_OG_TYPE
PassEnv STRAPDOWN_OG_URL
PassEnv STRAPDOWN_SHORTCUTICON
PassEnv STRAPDOWN_THEME
PassEnv STRAPDOWN_TITLE
